import { Campaign, Contact, Conversation } from "./types";
export const conversations: Conversation[] = [
  {
    id: "1",
    name: "Aarav Sharma",
    initials: "AS",
    message: "Yes, please share the pricing details.",
    time: "2m",
    unread: 3,
    status: "Open",
    tag: "Hot lead",
    color: "#7C5CFC",
  },
  {
    id: "2",
    name: "Meera Patel",
    initials: "MP",
    message: "Thank you! That works for us.",
    time: "18m",
    unread: 0,
    status: "Pending",
    tag: "Enterprise",
    color: "#4F7CFF",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    initials: "RM",
    message: "Can we schedule a demo tomorrow?",
    time: "42m",
    unread: 1,
    status: "Open",
    tag: "Demo",
    color: "#F59E0B",
  },
  {
    id: "4",
    name: "Ananya Iyer",
    initials: "AI",
    message: "The document has been received.",
    time: "1h",
    unread: 0,
    status: "Resolved",
    tag: "Customer",
    color: "#16C768",
  },
];
export const contacts: Contact[] = [
  {
    id: "1",
    name: "Aarav Sharma",
    phone: "+91 98765 43210",
    initials: "AS",
    tag: "Hot lead",
    lastSeen: "Active now",
    color: "#7C5CFC",
  },
  {
    id: "2",
    name: "Meera Patel",
    phone: "+91 98210 45521",
    initials: "MP",
    tag: "Enterprise",
    lastSeen: "12 min ago",
    color: "#4F7CFF",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    phone: "+91 97689 12345",
    initials: "RM",
    tag: "Demo",
    lastSeen: "Yesterday",
    color: "#F59E0B",
  },
];
export const campaigns: Campaign[] = [
  {
    id: "1",
    name: "Monsoon Upgrade Offer",
    status: "Running",
    sent: 3240,
    total: 5000,
    read: 78,
    replies: 312,
  },
  {
    id: "2",
    name: "July Product Update",
    status: "Scheduled",
    sent: 0,
    total: 2840,
    read: 0,
    replies: 0,
  },
  {
    id: "3",
    name: "Customer Feedback",
    status: "Completed",
    sent: 1280,
    total: 1280,
    read: 84,
    replies: 196,
  },
];
