import web from "./webTheme.json";
/** Shared web light theme. Regenerate webTheme.json with npm run theme:sync. */
export const ui = {
  primary: web.primary,
  primaryHover: web["primary-hover"],
  primaryStrong: web["primary-strong"],
  accent: web.accent,
  successSurface: web["success-surface"],
  secondary: web.secondary,
  secondaryForeground: web["secondary-foreground"],
  orange: web["brand-orange"],
  bg: web.background,
  bgCool: web["surface-subtle"],
  white: web.card,
  ink: web.foreground,
  body: web["muted-foreground"],
  muted: web["muted-foreground"],
  line: web.border,
  input: web.input,
  danger: web.destructive,
  dangerSurface: web["danger-surface"],
  warning: web.warning,
  dark: web["brand-ink"],
  success: web.success,
  ring: web.ring,
  sidebar: web.sidebar,
  sidebarAccent: web["sidebar-accent"],
  sidebarBorder: web["sidebar-border"],
} as const;
export const uiShadow = {
  shadowColor: ui.ink,
  shadowOpacity: 0.06,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 3 },
  elevation: 2,
} as const;
